// const passport = require("passport");
// const mongoose = require("mongoose");
var User = require('../models/user');
// const User = mongoose.model('users');
// var FacebookStrategy = require('passport-facebook').Strategy;
const keys = require("./keys");
const GitHubStrategy = require('passport-github').Strategy;

/////////////////////////
// CREREATE User Token from user info. We got user info
// from the GitHubStrategy callback function.
// That token will be put into a cookie
module.exports = function(passport){
  passport.serializeUser(function(user, done) {
    //this user._id is not the profile.id
    // this is the id automatically generated by mongo
    //this allows us to use mutiple OAuth providers without collision
    done(null, user._id);
  });

//Token stored in Cookie in browser is now deserialized to
//turn token into User
  passport.deserializeUser(function(id, done) {
    User.findById(id, function(err, user) {
      console.log('deserializing user:',user);
      done(err, user);
    });
  });

  passport.use(new GitHubStrategy({
    // clientID      : keys.githubClientID,
    // clientSecret  : keys.githubClientSecret,
    clientID      : "e06c0da38794ad51faf0",
    clientSecret  : "d270bfef0bc406b86da4b3095dff92cd83c7150a",
    // clientID      : keys.githubClientID || process.env.GITHUB_CLIENT_ID,
    // clientSecret  : keys.githubClientSecret || process.env.GITHUB_CLIENT_SECRET,
    // callbackURL: "https://127.0.0.1:3000/auth/github/callback",
    callbackURL   : "https://localhost:3000/auth/github/callback",
    // callbackURL: "/auth/github/callback",
    proxy         : true
  }, function(accessToken, refreshToken, profile, cb) {

    console.log(profile);
    User.findOrCreate({ 'gh.id' : profile.id }, function (err, user) {
      return cb(err, user);
    });


    // process.nextTick(function() {
    //
    //   User.findOne({ 'gh.id' : profile.id }, function(err, user) {
    //     if (err) return done(err);
    //     if (user) {
    //       return done(null, user);
    //     } else {
    //
    //       var newUser = new User();
    //       newUser.gh.id           = profile.id;
    //       newUser.gh.access_token = access_token;
    //       newUser.gh.firstName    = profile.name.givenName;
    //       newUser.gh.lastName     = profile.name.familyName;
    //       newUser.gh.email        = profile.emails[0].value;
    //
    //       newUser.save(function(err) {
    //         if (err)
    //           throw err;
    //
    //         return done(null, newUser);
    //       });
    //     }
    //
    //   });
    // });
  }));

}
